spring:
  # mysql数据库配置
  datasource:
    url: jdbc:mysql://112.74.41.146:3306/restaurant
    username: root
    password: qa5ATUHhMJS!5$OG
    hikari:
      maximum-pool-size: 60
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis账号密码
  redis:
    host: 112.74.41.146
    password: h0vnixnqlpGDX@Ue

#  #热部署生效
#  devtools:
#    restart:
#      enabled: true
#      #classpath目录下的WEB-INF文件夹内容修改不重启
#      exclude: resources/**
#      #设置重启的目录
#      additional-paths: src/main/java


# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker_str
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.firstGroup.restaurant.model
  configuration:
    map-underscore-to-camel-case: true

# 阿里云oss账号信息
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI5tAthXiqzCSghz8EX4VR
      keysecret: kfHG4ibZYv6SXiCRPn9BRy6WVSwa4N
      bucketname: edu-wuhaojie
logging:
  # 日志级别，可以打印sql语句
  level:
    com.firstGroup.restaurant: debug

